"""admins

Revision ID: 0fc90648ec72
Revises: 9b1dfda3ca32
Create Date: 2023-03-12 14:05:48.978878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc90648ec72'
down_revision = '9b1dfda3ca32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_unique_constraint(None, 'games', ['id'])
    op.create_foreign_key(None, 'games', 'players', ['cur_player_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_unique_constraint(None, 'players', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_table('admins')
    # ### end Alembic commands ###
