"""new_stats

Revision ID: 85c066e54a52
Revises: 0fc90648ec72
Create Date: 2023-03-18 20:42:07.487896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85c066e54a52"
down_revision = "0fc90648ec72"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "players_game_id_user_id_key", "players", type_="unique"
    )
    op.create_unique_constraint("player_uc", "players", ["game_id", "user_id"])
    op.add_column(
        "user_stats", sa.Column("count_games", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_stats", "count_games")
    op.drop_constraint("player_uc", "players", type_="unique")
    op.create_unique_constraint(
        "players_game_id_user_id_key", "players", ["game_id", "user_id"]
    )
    # ### end Alembic commands ###
